### ISSUE TITLE
Awesome!

### ISSUE THREAD

**Issue by gcormier** [rcalme/svg-to-stl#1]
Very cool!

I used this to get an STL to throw at my 3d printer that I put a pen on - turns it into a plotter!

**Comment by rcalme** [comment]
I hadn't even thought of that use-case. Can you post a picture of what your plotter created?

**Comment by gcormier** [comment]
![img_0282](https://cloud.githubusercontent.com/assets/8388983/20250452/c391b45a-a9dc-11e6-8dc0-2828398258bb.JPG)

Check it out!

It would be nice to deal with different colors through this tool, but I suspect that's out of scope and more easily dealt with the actual SVG in a graphics program.

There's also some funny business on the slicer end.. that little scooter is missing a few pieces that the slicer didn't use for some reason.
