### ISSUE TITLE
demo not working

### ISSUE THREAD

**Issue by Gotgot59** [rcalme/svg-to-stl#2]
I just want to do the conversion SVG to STL once, on the link you give.
But when i push the button nothing happen.

**Comment by rcalme** [comment]
Can you attach the SVG file?

There are some SVG formats that cannot be converted, and will peg your CPU (and likely freeze your browser tab).

Common file format problems are listed on the README, but I can look specifically at your file if you'd like.

**Comment by Gotgot59** [comment]
Sorry for the time of answer. 
I use : http://image.online-convert.com/ to create the SVG from a monochrome.
I try again same problem the re-render buttons doesn't works. 
here the file i try to convert. 
[chuck.svg.zip](https://github.com/rcalme/svg-to-stl/files/1049078/chuck.svg.zip)
