### ISSUE TITLE
Problems with convert objects from svg to stl

### ISSUE THREAD

**Issue by Minkalein** [rcalme/svg-to-stl#4]
Hi rcalme

We're two students and we're on the search of a simple way to convert an svg file into an stl file. We would like to draw objects and texts in a app that we develop and save it then as an svg file. Afterwards the file should be converted into a stl file thereby we can send it directly into cura (3D printer programm) and print it out as a 3D print.
We tried to upload objects like rectangles and circles, but it isn't visible on the right side or when, then only a part of it and only fullfilled objects (We need only the strokes). With texts there is no problem. What could be the reason for that? All of the files we are uploaded as a svg with saved paths (Adobe Illustratior). May you know a way to change the code that way so it would function?

Best wishes

Ramona

**Comment by rcalme** [comment]
Ramona,

This tool only works for closed shapes, as you see with text.

If you draw a "rectangle", which is actually four strokes, and not actually a closed shape, it will not work. Think about what it would mean to extrude a line in 3-dimensional space. A line has no thickness. If you extrude that into 3D space, you'd end up with a wall, again with no thickness, which would be impossible to 3D-print.

The thickness of the stroke in Illustrator is not taken into consideration.

* If you want a rectangle that is filled (becoming a box, in 3D space), an actual closed rectangle will get you that result.
* If you want a rectangle with a stroke thickness (becoming like a fence, in 3D space), a closed rectangle with another, smaller closed rectangle inside of it will get you that result. The space between the two rectangles is what will be extruded.
